//
// Created by Giacomo Balloccu on 18/01/2021.
//

#ifndef BIKEREDISTRIBUTIONHEURISTIC_PARTICLE_H
#define BIKEREDISTRIBUTIONHEURISTIC_PARTICLE_H


class Particle {

};


#endif //BIKEREDISTRIBUTIONHEURISTIC_PARTICLE_H
